### ISSUE TITLE
Не работает плагин "перенаправления"

### ISSUE THREAD

**Issue by sl3000** [asdbthemes/asdbturbo#3]
Те правила перенаправлений, которые уже есть, работают. 
Не работает вот как. 
В админке перехожу в закладку "404 ошибки", выбираю какую-то ошибку, нажимаю "добавить перенаправление", должна появится форма для добавления правила, но вместо этого совершается переход по ошибочной ссылке.
Еще такая ошибка возникает, не выбираются "все"строки (например ошибки) в списке. То есть я могу ставить галочку напротив каждой строки, но если ставлю "крыжик", что-бы выбрать все, то "все" не выбираются.

Если активировать другую тему или более раннюю версию этой, то все работает.

**Comment by wpbuild** [comment]
Исправлено
